# Generated by Django 5.0.2 on 2024-02-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение превью'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='счетчик просмотров'),
        ),
    ]
