# Generated by Django 5.0.2 on 2024-02-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateTimeField(default='значение отсутствует', verbose_name='дата производства'),
        ),
    ]
