# Generated by Django 4.2.2 on 2024-03-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Can publish product'), ('change_description', 'Can change product description'), ('change_category', 'Can change category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
